Hero
Sange1992/icecream pull request #37
Opened 2022-05-31 19:29 UTC by Elena-Nikolaevna

Кнопки исправила.
Стрелку поменяла из кнопки на ссылку. Прикрепила ссылку википедии на органическое молоко(на био эко нет).

2022-05-31 20:20 UTC, Sange1992 requested changes
нужно доработать

2022-05-31 20:20 UTC, Sange1992 commented on src/sass/layout/_hero.scss
> +    transition: all 1s linear;
Все работает, но возьми время и кубик из переменных, очень медлено)

2022-05-31 20:20 UTC, Sange1992 commented on src/sass/layout/_hero.scss
> +    transition: all 1s linear;
нас учили не использовать `all` укажи `focus` `hover`

2022-05-31 20:20 UTC, Sange1992 commented on src/sass/layout/_hero.scss
> +    transition-duration: 1000ms;
ты уже указала время `transition-duration` не нужно указывать, удали

2022-06-01 10:21 UTC, Elena-Nikolaevna commented on src/sass/layout/_hero.scss
> +    transition: all 1s linear;
указала

2022-06-01 10:22 UTC, Elena-Nikolaevna commented on src/sass/layout/_hero.scss
> +    transition: all 1s linear;
Кубик подставила

2022-06-01 13:49 UTC, Sange1992 approved these changes
ок)

2022-06-01 13:49 UTC, merged