Feature/about mob
Sange1992/icecream pull request #6
Opened 2022-05-29 07:03 UTC by an-na-kuzmina

2022-05-29 09:01 UTC, Sange1992 requested changes

2022-05-29 09:01 UTC, Sange1992 commented on src/sass/layout/_about.scss
> +    }
добавить `background-position: 0% **_75_**%;` второй параметр (сейчас 75% подбери по макету

2022-05-29 23:05 UTC, an-na-kuzmina commented
Исправила молоко в моб версии

2022-05-30 07:53 UTC, Sange1992 approved these changes
ок)

2022-05-30 07:53 UTC, merged